### ISSUE TITLE
Impossible to add openid-credentials node config

### ISSUE THREAD

**Issue by ager0sa** [ncarlier/node-red-contrib-openid#3]
Hello,

I can't add an openid-credentials node config, "add" button is always disabled.
Is this maybe an issue with the callback url ?

**Comment by ncarlier** [comment]
Hi,
the add button is disabled because you have to authenticate first: 
- Set your OIDC provider discovery URL (a URL ending with: .well-known/openid-configuration For example if your are using Google: https://accounts.google.com/.well-known/openid-configuration)
- Set Client ID and Secret created by your provider.
- Press authenticate button in order to start the authentication flow

The redirect URI of NodeRed have to be valid (and declared to your provider). This in order to pass access tokens from your provider  to NodeRED.

Regards.

**Comment by corlinski** [comment]
Hi
I have the same problem. I even passed authentication and received tokens.
It seems there is no field to add openid-credentials config node name (displayName). 
When I add credentials and sucessfully authenticate the code seems to expect displayName - but the field is hidden.

**Comment by ncarlier** [comment]
Hi, you were right about that. The extraction of the display name was not correct.
Thank you!
